config/routes.rb
Rails.application.routes.draw do
  resources :flats

  root to: "flats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(params_flat)
    @flat.save
    redirect_to flats_path
  end

  def edit
  end

  def update
    @flat.update(params_flat)
    redirect_to flats_path
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def params_flat
    params.require(:flat).permit(:name, :address, :price_per_night, :number_of_guests, :description)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Edit the flat</h1>

<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Edit your flat", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back to all flats", flats_path, class: "btn btn-primary margintop10" %>

app/views/flats/index.html.erb
<h1>All flats (<%= @flats.length%>)</h1>

<div class="row">
  <% @flats.each do |flat| %>
      <div class="col-xs-12 col-sm-4">
        <div class="flat-card">
          <div class="flat-card-top">
            <h3><%= flat.name %></h3>
            <p><%= flat.address %></p>
            <ul class="list-inline">
              <li> <i class="fas fa-user-alt"> </i></li>
              <li> <%= flat.number_of_guests %> </li>
              <li> <i class="fas fa-euro-sign"></i> </li>
              <li> <%= flat.price_per_night %> </li>
            </ul>
          </div>
          <div class="flat-card-bottom">
            <%=link_to "More info", flat_path(flat)%>
            <%=link_to "Edit", edit_flat_path(flat)%>
            <%=link_to "Delete", flat_path(flat),  method: :delete, data: { confirm: "Are you sure?" }%>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>Create a new flat</h1>

<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "add your flat", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back to all flats", flats_path, class: "btn btn-primary margintop10" %>

app/views/flats/show.html.erb
<div class="flat-box">
  <div class="details-cards">
    <div class="details-card">
      <p><%= @flat.name %></p>
      <p><%= @flat.address %></p>
    </div>
    <div class="details-card">
      <p><%= @flat.description %></p>
    </div>
    <div class="details-card">
      <p><%= @flat.price_per_night %> € </p>
      <p><%= @flat.number_of_guests  %> guest</p>
    </div>
  </div>

  <div class="flat-show-card">
    <h5>Book this place!</h5>
    <form action="">
      <div class="input-group">
        <span class="input-group-addon" id="basic-addon1">From:</span>
        <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
      </div>
      <div class="input-group mt-2">
        <span class="input-group-addon" id="basic-addon1">To:</span>
        <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
      </div>
      <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
    </form>
  </div>
</div>

<%= link_to "Back to all flats", flats_path, class: "btn btn-primary margintop10" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="background-white">
    <%= render "shared/navbar" %>
    <% if params['controller'] == "flats" && params['action'] == "show" %>
      <div class="wrapper_image">
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "Simple Airbnb", "/", class: "navbar-wagon-item navbar-wagon-link" %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Add flat", new_flat_path, class: "btn btn-primary" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>